################################################################################
#
# ESCPR
#
################################################################################

ESCPR_VERSION = master
ESCPR_SOURCE = epson-inkjet-printer-escpr-1.6.4-1lsb3.2.tar.gz
ESCPR_SITE = https://download3.ebz.epson.net/dsc/f/03/00/04/37/97/88177bc0dc7025905eae4a0da1e841408f82e33c

ESCPR_DEPENDENCIES = host-autoconf

# The bundled configure script is generated by autoconf 2.13 and doesn't
# detect cross-compilation correctly. Therefore, we have to regenerate it.
# We need to pass -I because of the non-standard m4 directory name, and
# none of the other autotools are used, so the below is the easiest.
#define ESCPR_RUN_AUTOCONF
#	(cd $(@D); $(HOST_DIR)/usr/bin/autoreconf -ivf)
#endef
#ESCPR_PRE_CONFIGURE_HOOKS += ESCPR_RUN_AUTOCONF

$(eval $(autotools-package))
